export const getRandomOssorGloss = () => {
    const osses = [
        "Kincsem",
        "Black Caviar",
        "Peppers Pride",
        "Eclipse",
        "Karayel",
        "Ormonde",
        "Prestige",
        "Ribot",
        "Colin",
        "Macón",
        "Tsurumaru Sunday",
        "Frankel",
        "Highflyer",
        "Nearco",
        "Barcaldine",
        "Personal Ensign",
        "Tremont",
        "Ardrossan",
        "Asteroid",
        "Braque",
        "Crucifix",
        "Goldfinder",
        "Kurifuji",
        "Handsomchamp",
        "Nereide",
        "Tokino Minoru",
        "Bahram",
        "Combat",
        "Grand Flaneur",
        "Moscona",
        "Patience",
        "Regulus",
        "St. Simon",
        "Alipes",
        "American Eclipse",
        "Bullets Fever",
        "Caracalla",
        "Derek",
        "La Cressonniere",
        "Maruzensky",
    ];

    const glosses = [
        "SUMPTUOUS PLUM",
        "BERRY SMOOTHIE",
        "SWEET FONDANT",
        "SWEET PINK",
        "PRETTY PINK",
        "PALE PEONY",
        "SPRING ROSE",
        "PEPPER RED",
        "ROASTED RED",
        "RASPBERRY BELLINI",
        "FLAMINGO FLOCK",
        "CHERRY PLUM",
        "BLUSH PINK",
        "SPRING BLUSH",
        "RUBY STARLET",
        "REDCURRANT GLORY",
        "RASPBERRY DIVA",
        "PRESSED PETAL",
        "PINK PARCHMENT",
        "BLOSSOM TREE",
        "JASMINE SHIMMER",
        "CORAL FLAIR",
        "SALSA MIX",
        "COPPER BLUSH",
        "SUNSET KISS",
        "SOFT PEACH",
        "SOFT CORAL",
        "DELICATE VEIL",
        "ORANGE FIZZ",
        "TANGERINE TWIST",
        "MOROCCAN FLAME",
        "SUNBAKED TERRACOTTA",
        "APRICOT CRUSH",
        "APRICOT WHITE",
        "HONEY BEAM",
        "CINNAMON SPRINKLE",
        "FROSTED PAPAYA",
        "POACHED PEACH",
        "BANANA SPLIT",
        "COCOA BUTTER",
        "HONEYSUCKLE",
        "DESERT WIND",
        "CHERISHED GOLD",
        "GOLDEN SANDS",
        "COUNTY CREAM",
        "LEMON TROPICS",
        "WILD PRIMROSE",
        "DAFFODIL WHITE",
        "LUNAR FALLS",
        "HONEY MUSTARD",
        "MOLTEN YELLOW",
        "LEMON PUNCH",
        "LEMON ZEST",
        "LEMON PIE",
        "VANILLA SUNDAE",
        "PRIMROSE WHITE",
        "MOUNTAIN MOSS",
        "LUSCIOUS LIME",
        "KIWI CRUSH",
        "MELON SORBET",
        "FRESH STEM",
        "SOFT APPLE",
        "LEMON SPIRIT",
        "PINE NEEDLE",
        "GUILD GREEN",
        "OVERTLY OLIVE",
        "FOSSIL TRACE",
        "FRESH ARTICHOKE",
        "MOSSY STONE",
        "APPLE WHITE",
        "EMERALD GLADE",
        "VILLAGE MAZE",
        "FRESH FOLIAGE",
        "DEWY LAWN",
        "WILLOW TREE",
        "WELLBEING",
        "NORDIC SPA",
        "FORTUNE GREEN",
        "PROUD PEACOCK",
        "TEAL VOYAGE",
        "COASTAL GREY",
        "MINT MACAROON",
        "PEPPERMINT CANDY",
        "DRIFTING CLOUD",
        "TEAL TENSION",
        "TEAL TOUCH",
        "TRANQUIL DEPTHS",
        "MARINE SPLASH",
        "LAGOON FALLS",
        "OCEAN RIPPLE",
        "JADE WHITE",
        "INDIGO SHADE",
        "DENIM DRIFT",
        "STONEWASHED BLUE",
        "NORDIC SKY",
        "FIRST DAWN",
        "MINERAL MIST",
        "ATMOSPHERE",
        "SAPPHIRE SALUTE",
        "WOAD WALK",
        "STRIKING CYAN",
        "DELFT CHINA",
        "BLUE BABE",
        "BLISSFUL BLUE",
        "BLUEBERRY WHITE",
        "REGAL PURPLE",
        "PRESSED BLUEBERRY",
        "SPRING CROCUS",
        "BLUE INCENSE",
        "LAVENDER QUARTZ",
        "MAUVE CLOUD",
        "COTTON BREEZE",
        "BLACKBERRY BUSH",
        "PURPLE POUT",
        "PASSION FLOWER",
        "FROSTED GRAPE",
        "LILAC ROSE",
        "GENTLE LAVENDER",
        "VIOLET WHITE",
        "MULBERRY BURST",
        "ROSE BARK",
        "HEART WOOD",
        "DUSTED FONDANT",
        "MELLOW MOCHA",
        "ALMOST OYSTER",
        "NUTMEG WHITE",
        "CHERRY CHOCOLATE",
        "WOVEN WILLOW",
        "SOFT TRUFFLE",
        "MUDDY PUDDLE",
        "SOFT STONE",
        "GENTLE FAWN",
        "MALT CHOCOLATE",
        "PINE CONE",
        "VINTAGE SMOKE",
        "WOODED SOLACE",
        "PERFECTLY TAUPE",
        "PRESSED PUTTY",
        "MUTED BLUSH",
        "JUST WALNUT",
        "SADDLE BROWN",
        "MALTED CARAMEL",
        "COOKIE DOUGH",
        "CARAMEL LATTE",
        "SANDSTONE",
        "NATURAL HESSIAN",
        "SUMMER LINEN",
        "URBAN WALK",
        "ICED FRAPPE",
        "ENGLISH ELM",
        "DUNE GRASS",
        "PEBBLE SHORE",
        "EGYPTIAN COTTON",
        "WELSH FLINT",
        "BUTTERMILK",
        "IVORY",
        "NATURAL WICKER",
        "MAGNOLIA",
        "GARDENIA",
        "BARLEY WHITE",
        "NATURAL CALICO",
        "ELDERFLOWER TEA",
        "ORCHID WHITE",
        "ALMOND WHITE",
        "VANILLA WHITE",
        "IVORY LACE",
        "COASTAL GLOW",
        "FINE CREAM",
        "MOON SHIMMER",
        "MORNING LIGHT",
        "TIMELESS",
        "FROSTED DAWN",
        "JASMINE WHITE",
        "WHITE COTTON",
        "ABSOLUTE WHITE",
        "NOBLE GREY",
        "NATURAL SLATE",
        "EARL BLUE",
        "DOVE",
        "MISTY MIRROR",
        "FROSTED STEEL",
        "CORNFLOWER WHITE",
        "JAVELIN",
        "DEEP FOSSIL",
        "GOOSEWING",
        "SILVER SHORES",
        "GOOSE DOWN",
        "GREY WISP",
        "WHITE MIST",
        "RICH BLACK",
        "URBAN OBSESSION",
        "WARM PEWTER",
        "CHIC SHADOW",
        "POLISHED PEBBLE",
        "SWANSDOWN",
        "ROCK SALT",
        "BRAVE GROUND",
        "TRANQUIL DAWN",
    ];

    const ossAndGloss = [
        ...osses.map((name) => {
            return { name: name.toUpperCase(), type: "Horse" };
        }),
        ...glosses.map((name) => {
            return { name: name, type: "Gloss" };
        }),
    ];

    return ossAndGloss[Math.floor(Math.random() * ossAndGloss.length)];
};
